# Generated by Django 6.0.1 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worship',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
